FROM openjdk:8-jdk-alpine

RUN apk add --no-cache git git-lfs openssh-client curl unzip bash ttf-dejavu coreutils tini

ARG user                                        
ARG group                                       
ARG uid                                         
ARG gid          
ARG http_port
ARG agent_port         
ARG JENKINS_VERSION
ARG JENKINS_SHA
ARG JENKINS_HOME
ARG REF


ENV user=${user:-cuong}
ENV group=${group:-cuong}                                    
ENV uid=${uid:-1001}
ENV gid=${gid:-1001}        
ENV http_port=${http_port:-8080}
ENV JENKINS_SLAVE_AGENT_PORT=${agent_port:-50000}       
ENV JENKINS_VERSION ${JENKINS_VERSION:-2.204.5}   
ENV JENKINS_SHA ${JENKINS_SHA:-94c73fa5b72e0a4eb52c5c99c08351f85a51d138f3dbaff6f64e4406353f839c} 

ENV JENKINS_HOME=${JENKINS_HOME:-/var/jenkins_home}
ENV REF=${REF:-/usr/share/jenkins/ref}

# Jenkins is run with user `jenkins`, uid = 1000
# If you bind mount a volume from the host or a data container,
# ensure you use the same uid
RUN mkdir -p $JENKINS_HOME \
  && chown ${uid}:${gid} $JENKINS_HOME \
  && addgroup -g ${gid} ${group} \
  && adduser -h "$JENKINS_HOME" -u ${uid} -G ${group} -s /bin/bash -D ${user}

# Jenkins home directory is a volume, so configuration and build history
# can be persisted and survive image upgrades
VOLUME $JENKINS_HOME

# $REF (defaults to `/usr/share/jenkins/ref/`) contains all reference configuration we want
# to set on a fresh new installation. Use it to bundle additional plugins
# or config file with your custom jenkins Docker image.
RUN mkdir -p ${REF}/init.groovy.d

# Can be used to customize where jenkins.war get downloaded from
ARG JENKINS_URL=https://repo.jenkins-ci.org/public/org/jenkins-ci/main/jenkins-war/${JENKINS_VERSION}/jenkins-war-${JENKINS_VERSION}.war

# could use ADD but this one does not check Last-Modified header neither does it allow to control checksum
# see https://github.com/docker/docker/issues/8331
RUN curl -fsSL ${JENKINS_URL} -o /usr/share/jenkins/jenkins.war \
  && echo "${JENKINS_SHA}  /usr/share/jenkins/jenkins.war" | sha256sum -c -

ENV JENKINS_UC https://updates.jenkins.io
ENV JENKINS_UC_EXPERIMENTAL=https://updates.jenkins.io/experimental
ENV JENKINS_INCREMENTALS_REPO_MIRROR=https://repo.jenkins-ci.org/incrementals
RUN chown -R ${user} "$JENKINS_HOME" "$REF"

# for main web interface:
EXPOSE ${http_port}

# will be used by attached slave agents:
EXPOSE ${agent_port}

ENV COPY_REFERENCE_FILE_LOG $JENKINS_HOME/copy_reference_file.log

USER ${user}

COPY jenkins-support /usr/local/bin/jenkins-support
COPY jenkins.sh /usr/local/bin/jenkins.sh
COPY tini-shim.sh /bin/tini
ENTRYPOINT ["/sbin/tini", "--", "/usr/local/bin/jenkins.sh"]

# from a derived Dockerfile, can use `RUN plugins.sh active.txt` to setup $REF/plugins from a support bundle
COPY plugins.sh /usr/local/bin/plugins.sh
COPY install-plugins.sh /usr/local/bin/install-plugins.sh
